dbfilename redis_queue.rdb
dir /workspaces/ERPnext/frappe-bench/config/pids
pidfile /workspaces/ERPnext/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /workspaces/ERPnext/frappe-bench/config/redis_queue.acl
